/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package midterm_project_gui;
import javax.swing.*;
/**
 *
 * @author Jimuel
 */
public class Knapsack1 extends javax.swing.JFrame {

    /**
     * Creates new form Knapsack1
     */
    public Knapsack1() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Weight_Label = new javax.swing.JLabel();
        Weight_Input = new javax.swing.JTextField();
        Product_Scroll_Pane = new javax.swing.JScrollPane();
        Product_Table = new javax.swing.JTable();
        Proceed_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Midterm Project");

        Weight_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Weight_Label.setText("Weight gross of the motor vehicle (Type 1 to 15 only):");

        Weight_Input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Weight_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Weight_InputActionPerformed(evt);
            }
        });

        Product_Scroll_Pane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Product_Scroll_Pane.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Product_Scroll_Pane.setHorizontalScrollBar(null);

        Product_Table.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        Product_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Soap",  new Double(7.0),  new Integer(500)},
                {"Noodles",  new Double(2.5),  new Integer(375)},
                {"Canned Goods",  new Double(5.0),  new Integer(450)},
                {"Cooking Oil",  new Double(3.0),  new Integer(725)}
            },
            new String [] {
                "Product Name", "Weight/Box", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Product_Scroll_Pane.setViewportView(Product_Table);

        Proceed_Button.setText("Proceed");
        Proceed_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proceed_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Proceed_Button)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Product_Scroll_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Weight_Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Weight_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Weight_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Weight_Input, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Product_Scroll_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Proceed_Button)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Weight_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Weight_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Weight_InputActionPerformed

    private void Proceed_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proceed_ButtonActionPerformed
        double input = 0;
        
        try {// Convert input String to double with error handling
            input = Double.parseDouble(Weight_Input.getText());
        } catch (NumberFormatException e) {
        }        
        
        if(input >= 1 && input <= 15){// If input number is between 1 to 15, go to next window
            Knapsack2 knapsackResults = new Knapsack2(Weight_Input.getText());
            knapsackResults.setVisible(true);
            this.dispose();
        }
        
        else{// Else display error message 
            JOptionPane.showMessageDialog(this, 
                    "Invalid input! Input only from 1 to 15", 
                    "Error", // Title of the dialog
                    JOptionPane.ERROR_MESSAGE); // Message type
        }
    }//GEN-LAST:event_Proceed_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Knapsack1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Knapsack1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Knapsack1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Knapsack1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Knapsack1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Proceed_Button;
    private javax.swing.JScrollPane Product_Scroll_Pane;
    private javax.swing.JTable Product_Table;
    private javax.swing.JTextField Weight_Input;
    private javax.swing.JLabel Weight_Label;
    // End of variables declaration//GEN-END:variables
}
