/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package midterm_project_gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jimuel
 */
public class StringMatching extends javax.swing.JFrame {

    /**
     * Creates new form StringMatching
     */
    public StringMatching() {
        initComponents();
    }
    
    public StringMatching(String address) {
        initComponents();
        this.Address_Input.setText(address);
    }
    
    // String matching algorithm
    public static String[] searchWordInString(String address, String word) {
        // Convert both text and word to lowercase to make the search case-insensitive
        String lowerText = address.toLowerCase();
        String lowerWord = word.toLowerCase();

        int wordCount = 0;
        List<Integer> positions = new ArrayList<>();

        // Split the lowerText into words using space as delimiter
        String[] words = lowerText.split(" ");
        
        for (int i = 0; i < words.length; i++) {
            if (words[i].equals(lowerWord)) {
                wordCount++;
                positions.add(i + 1); // Add 1 to make position human-readable (starting from 1 instead of 0)
            }
        }

        // Convert wordCount and positions to strings
        String wordCountString = Integer.toString(wordCount);
        String wordPositionString = positions.isEmpty() ? "" : String.join(", ", positions.stream().map(Object::toString).toArray(String[]::new));

        return new String[]{wordCountString, wordPositionString};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Address_Input_Label = new javax.swing.JLabel();
        Address_Input = new javax.swing.JLabel();
        Search_Input_Label = new javax.swing.JLabel();
        Search_Input = new javax.swing.JTextField();
        Search_Button = new javax.swing.JButton();
        Occurences_Input_Label = new javax.swing.JLabel();
        Occurences_Input = new javax.swing.JLabel();
        Position_Input_Label = new javax.swing.JLabel();
        Position_Input = new javax.swing.JLabel();
        Proceed_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Midterm Project");

        Address_Input_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Address_Input_Label.setText("Address:");

        Address_Input.setText("Address");

        Search_Input_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Search_Input_Label.setText("Search for word in address:");

        Search_Input.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Search_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_InputActionPerformed(evt);
            }
        });

        Search_Button.setText("Search");
        Search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ButtonActionPerformed(evt);
            }
        });

        Occurences_Input_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Occurences_Input_Label.setText("No of occurences:");

        Occurences_Input.setText("-");

        Position_Input_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Position_Input_Label.setText("Word's position:");

        Position_Input.setText("-");

        Proceed_Button.setText("Proceed");
        Proceed_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proceed_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Position_Input_Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Position_Input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Occurences_Input_Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Occurences_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Search_Input_Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Search_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Search_Button))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Address_Input_Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Address_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Proceed_Button)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address_Input_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_Input_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Input)
                    .addComponent(Search_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Occurences_Input_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Occurences_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Position_Input_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Position_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(Proceed_Button)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Search_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_InputActionPerformed

    private void Search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ButtonActionPerformed
        
        if(this.Search_Input.getText().isBlank()){
            JOptionPane.showMessageDialog(this,
                "Missing word to search!",
                "Error", // Title of the dialog
                JOptionPane.ERROR_MESSAGE); // Message type
        }
        
        else{
            String address = this.Address_Input.getText();
            String word = this.Search_Input.getText();
            
            address = address.replace(",", ""); // Remove the commas in address before string matching
            
            String[] result = searchWordInString(address, word);
            this.Occurences_Input.setText(result[0]);
            this.Position_Input.setText(result[1]);
        }        
    }//GEN-LAST:event_Search_ButtonActionPerformed

    private void Proceed_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proceed_ButtonActionPerformed

        ExitProgram exitWindow = new ExitProgram();
        exitWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Proceed_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StringMatching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StringMatching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StringMatching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StringMatching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StringMatching().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_Input;
    private javax.swing.JLabel Address_Input_Label;
    private javax.swing.JLabel Occurences_Input;
    private javax.swing.JLabel Occurences_Input_Label;
    private javax.swing.JLabel Position_Input;
    private javax.swing.JLabel Position_Input_Label;
    private javax.swing.JButton Proceed_Button;
    private javax.swing.JButton Search_Button;
    private javax.swing.JTextField Search_Input;
    private javax.swing.JLabel Search_Input_Label;
    // End of variables declaration//GEN-END:variables
}
